ip:
  base: 119.3.80.210

user:
  default:
    # 用户名的默认前缀
    username: user
    # 用户的默认头像
    avatar: https://i.loli.net/2019/10/19/ndiyj3fzrwxv2co.jpg

server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: service-product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: aA111111
    url: jdbc:mysql://${ip.base}:3306/exam?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 100MB # 最大支持文件大小
      max-request-size: 100MB # 最大支持请求大小

# 拦截器相关的配置
interceptors:
  # 不需要进行鉴权的接口地址，用逗号隔开
  auth-ignore-uris: /api/user/register,/api/user/login